//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExsalesMobileApp.lang {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LangResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExsalesMobileApp.lang.LangResources", typeof(LangResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Function.
        /// </summary>
        public static string AccountPageButtonFunction {
            get {
                return ResourceManager.GetString("AccountPageButtonFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Personal data.
        /// </summary>
        public static string AccountPageButtonPersonalData {
            get {
                return ResourceManager.GetString("AccountPageButtonPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Get Started.
        /// </summary>
        public static string AccountPageFunctionLabelText {
            get {
                return ResourceManager.GetString("AccountPageFunctionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your personal information.
        /// </summary>
        public static string AccountPagePersonalDataLabelText {
            get {
                return ResourceManager.GetString("AccountPagePersonalDataLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your current role is.
        /// </summary>
        public static string AccountPageRoleTextLabel {
            get {
                return ResourceManager.GetString("AccountPageRoleTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome, .
        /// </summary>
        public static string AccountPageWelcomeText {
            get {
                return ResourceManager.GetString("AccountPageWelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back.
        /// </summary>
        public static string PageBack {
            get {
                return ResourceManager.GetString("PageBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string PersonPageButtonEditText {
            get {
                return ResourceManager.GetString("PersonPageButtonEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string PersonPageButtonSaveText {
            get {
                return ResourceManager.GetString("PersonPageButtonSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your email.
        /// </summary>
        public static string PersonPageEmailLabelText {
            get {
                return ResourceManager.GetString("PersonPageEmailLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Put your email.
        /// </summary>
        public static string PersonPageEmailPlaceholder {
            get {
                return ResourceManager.GetString("PersonPageEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First name.
        /// </summary>
        public static string PersonPageFirstNameLabelText {
            get {
                return ResourceManager.GetString("PersonPageFirstNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Put your first name.
        /// </summary>
        public static string PersonPageFirstNamePlaceholder {
            get {
                return ResourceManager.GetString("PersonPageFirstNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last name.
        /// </summary>
        public static string PersonPageLastNameLabelText {
            get {
                return ResourceManager.GetString("PersonPageLastNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Put your last name.
        /// </summary>
        public static string PersonPageLastNamePlaceholder {
            get {
                return ResourceManager.GetString("PersonPageLastNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your phone.
        /// </summary>
        public static string PersonPagePhoneLabelText {
            get {
                return ResourceManager.GetString("PersonPagePhoneLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Put your phone.
        /// </summary>
        public static string PersonPagePhonePlaceholder {
            get {
                return ResourceManager.GetString("PersonPagePhonePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your personal information.
        /// </summary>
        public static string PersonPageTitleLabelText {
            get {
                return ResourceManager.GetString("PersonPageTitleLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send.
        /// </summary>
        public static string RegPageBtSend {
            get {
                return ResourceManager.GetString("RegPageBtSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check the specified data and select a role!.
        /// </summary>
        public static string RegPageDataError {
            get {
                return ResourceManager.GetString("RegPageDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Put email.
        /// </summary>
        public static string RegPageEmailPlaceholder {
            get {
                return ResourceManager.GetString("RegPageEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The password will be sent to the specified email.
        /// </summary>
        public static string RegPageLabelRegText {
            get {
                return ResourceManager.GetString("RegPageLabelRegText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Role.
        /// </summary>
        public static string RegPagePickerTitle {
            get {
                return ResourceManager.GetString("RegPagePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manager:Seller.
        /// </summary>
        public static string RegPageRoles {
            get {
                return ResourceManager.GetString("RegPageRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Register.
        /// </summary>
        public static string StartPageBtRegister {
            get {
                return ResourceManager.GetString("StartPageBtRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign In.
        /// </summary>
        public static string StartPageBtSignIn {
            get {
                return ResourceManager.GetString("StartPageBtSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authorisation Error. Check the information provided!.
        /// </summary>
        public static string StartPageEnterMessageWarning {
            get {
                return ResourceManager.GetString("StartPageEnterMessageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create new account?.
        /// </summary>
        public static string StartPageLabelRegister {
            get {
                return ResourceManager.GetString("StartPageLabelRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string StartPageLoginPassword {
            get {
                return ResourceManager.GetString("StartPageLoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string StartPageLoginPlaceholder {
            get {
                return ResourceManager.GetString("StartPageLoginPlaceholder", resourceCulture);
            }
        }
    }
}
